apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: sunsplash/docker-demo-complex-api
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD #our api image is looking for an env variable of PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword #find k8s secret of name pgpassword
                  key: PGPASSWORD #find key of PGPASSWORD in secret of name pgpassword