apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetesdemo-net-tls
spec:
  secretName: kubernetesdemo-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetesdemo.net
  dnsNames:
    - kubernetesdemo.net
    - www.kubernetesdemo.net